In [1]:
import numpy as np
import matplotlib.pyplot as plt
from pprint import pprint

In [13]:
CF = np.array([-100,80,90,10])
rate = 0.4622
maturity = CF.shape[0]-1

discount_factors = 1/(1+rate)**np.arange(0,maturity+1)
NPV = np.dot(CF, discount_factors)

print(NPV)


0.005671444260690439


In [27]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
# Calculate an NPV curve for various interest rates
rates = np.arange(0.0, 2, 0.5)
rates_idmat = np.diag(rates)

# discount_matrix = 1/(1+rate)**np.arange(0,maturity+1)

print(rates)
# print(discount_matrix)

[[0.  0.  0.  0. ]
 [0.  0.5 0.  0. ]
 [0.  0.  1.  0. ]
 [0.  0.  0.  1.5]]
